select user
from dual;
-- sapiens


select *
from party_member;

select *
from party_apply;

select *
from party_message;

         

SELECT A.APPLY_ID, B.NICKNAME, C.GENDER,FN_GET_MANNER(A.USER_ID) , A.APPLY_MESSAGE
FROM PARTY_APPLY A
JOIN USER_ACCOUNT B
ON A.USER_ID = B.USER_ID
JOIN USER_INFO C
ON A.USER_ID = C.USER_ID
WHERE NOT EXISTS 
(
    SELECT 1
    FROM PARTY_MEMBER D
    WHERE D.APPLY_ID = A.APPLY_ID
)
;

SELECT *         
FROM USER_ACCOUNT;
         
SELECT A.APPLY_ID AS applyId, B.NICKNAME AS name, C.GENDER AS gender,FN_GET_USER_AGE(C.BIRTHDATE) AS age,FN_GET_MANNER(A.USER_ID) AS temp, A.APPLY_MESSAGE AS applyComment
FROM PARTY_APPLY A
JOIN USER_ACCOUNT B
ON A.USER_ID = B.USER_ID
JOIN USER_INFO C
ON A.USER_ID = C.USER_ID
WHERE NOT EXISTS 
(
    SELECT 1
    FROM PARTY_MEMBER D
    WHERE D.APPLY_ID = A.APPLY_ID
)
;

SELECT FN_GET_USER_AGE(BIRTHDATE)
FROM USER_INFO;

/*
CREATE FUNCTION FN_GET_USER_AGE
(
    P_BIRTHDATE DATE
)
RETURN NUMBER
IS
    V_AGE NUMBER;
    
BEGIN
    
    V_AGE := TRUNC(MONTHS_BETWEEN(SYSDATE,P_BIRTHDATE)/12);
    
    RETURN V_AGE;
END;
*/

/*
CREATE VIEW VW_PARTY_ACTIVE_MEMBER 
AS
SELECT A.PARTY_ID,B.USER_ID AS USER_ID , NULL AS MEMBER_ID, B.NICKNAME, FN_GET_USER_AGE(C.BIRTHDATE) AS AGE, C.GENDER, FN_GET_MANNER(A.USER_ID) AS TEMP, 'READY' AS READY, 'HOST' AS POSITION
FROM PARTY A
JOIN USER_ACCOUNT B
ON A.USER_ID = B.USER_ID
JOIN USER_INFO C
ON A.USER_ID = C.USER_ID
UNION ALL
SELECT B.PARTY_ID,B.USER_ID AS USER_ID, A.MEMBER_ID, C.NICKNAME, FN_GET_USER_AGE(D.BIRTHDATE), D.GENDER, FN_GET_MANNER(B.USER_ID), 
CASE WHEN (FN_GET_PARTY_LAST_UPDATE_TIME(B.PARTY_ID) < A.READY_AT) 
THEN 'READY' 
ELSE 'UNREADY'
END AS READY
, 'CREW'
FROM PARTY_MEMBER A
JOIN PARTY_APPLY B
ON A.APPLY_ID = B.APPLY_ID
JOIN USER_ACCOUNT C
ON B.USER_ID = C.USER_ID
JOIN USER_INFO D
ON B.USER_ID = D.USER_ID
JOIN PARTY E
ON B.PARTY_ID = E.PARTY_ID
WHERE
NOT EXISTS
(
    SELECT 1
    FROM PARTY_KICK F
    WHERE F.MEMBER_ID = A.MEMBER_ID
)
;
*/

/*
CREATE OR REPLACE FUNCTION FN_GET_PARTY_LAST_UPDATE_TIME
(
    P_PARTY_ID NUMBER
)
RETURN DATE
IS
    V_LAST_UPDATE DATE;
BEGIN

    SELECT NVL(MAX(T.CREATED_AT),null) INTO V_LAST_UPDATE
    FROM 
    (
        SELECT CREATED_AT
        FROM PARTY_ROOM
        WHERE PARTY_ID = P_PARTY_ID
        UNION
        SELECT CREATED_AT
        FROM PARTY_MEMBER A
        JOIN PARTY_APPLY B
        ON A.APPLY_ID = B.APPLY_ID
        WHERE B.PARTY_ID = P_PARTY_ID
    ) T;
    
    RETURN V_LAST_UPDATE;
    
END;
*/



SELECT A.MESSAGE_ID, B.NICKNAME, A.CONTENT, A.USER_ID, A.CREATED_AT
FROM PARTY_MESSAGE A
JOIN USER_ACCOUNT B
ON A.USER_ID = B.USER_ID
WHERE A.PARTY_ID = 1
ORDER BY CREATED_AT
;


SELECT *
FROM PARTY_DROP;

SELECT *
FROM PARTY;




SELECT *
FROM PARTY_APPLY;


INSERT INTO PARTY_APPLY(APPLY_ID, PARTY_ID, USER_ID,APPLY_MESSAGE, CREATED_AT)
VALUES(PARTY_APPLY_SEQ.NEXTVAL,#{partyId},#{userId},#{applyComment},SYSDATE)
;

			<span>주열룸</span>
					</div>
					
					<div class="theme-info">
						<span>우주별&nbsp;&nbsp;</span>
						<span>그레이&nbsp;&nbsp;</span>
						<span>2026-06-01&nbsp;&nbsp;</span>
						<span>18:00&nbsp;&nbsp;</span>
						<span>2명 ~ 4명</span>
						<span>30000</span>
						<span>예약 가능/예약 불가</span>
					</div>
					
					<div class="party-condition">
						<span>성별 동성/무관</span>
						<span>미쿠 좋아하는 사람만 오셈</span>						
					</div> 

SELECT E.CAFE_NAME, D.ROOM_NAME
, TO_CHAR(C.OPEN_AT,'YYYY-MM-DD')
, TO_CHAR(C.OPEN_AT,'HH24:MI')
, D.MIN_PLAYERS, D.MAX_PLAYERS
, D.PRICE, FN_RESERVATION_CHECK(C.RES_OPEN_ID)
, F.GENDER_NAME, A.MESSAGE
FROM PARTY A
JOIN PARTY_ROOM B
ON A.PARTY_ID = B.PARTY_ID
JOIN RES_OPEN C
ON B.RES_OPEN_ID = C.RES_OPEN_ID
JOIN ROOM D
ON C.ROOM_ID = D.ROOM_ID
JOIN CAFE E
ON D.CAFE_ID = E.CAFE_ID
JOIN GENDER_CONDITION F
ON F.GENDER_ID = A.GENDER_ID
WHERE A.PARTY_ID = 1
;



SELECT *
FROM PARTY_DROP;



SELECT *
FROM RESERVATION;

SELECT *
FROM RESERVATION_CANCEL;


/*
CREATE OR REPLACE FUNCTION FN_GET_PARTY_CONDITION
(
    P_PARTY_ID NUMBER
)
RETURN VARCHAR2
IS
    V_DROP NUMBER;
    V_RESERVATION NUMBER;
    
    V_COUNT NUMBER;
    V_MAX NUMBER;
    
BEGIN
    
    SELECT COUNT(*) INTO V_DROP
    FROM PARTY_DROP
    WHERE PARTY_ID = P_PARTY_ID;
    
    IF (V_DROP > 0) THEN
        RETURN '취소된 파티';
    END IF;
    
    SELECT COUNT(*) INTO V_RESERVATION
    FROM RESERVATION A
    WHERE A.PARTY_ID = P_PARTY_ID AND NOT EXISTS
    (
        SELECT 1
        FROM RESERVATION_CANCEL B
        WHERE A.RESERVATION_ID = B.RESERVATION_ID
    );
    
    IF(V_RESERVATION > 0) THEN
        RETURN '예약된 파티';
    END IF;

    SELECT COUNT(*) INTO V_COUNT
    FROM VW_PARTY_ACTIVE_MEMBER
    WHERE PARTY_ID = P_PARTY_ID;
    
    SELECT NVL(C.MAX_PLAYERS,0) INTO V_MAX
    FROM PARTY_ROOM A
    JOIN RES_OPEN B
    ON A.RES_OPEN_ID = B.RES_OPEN_ID
    JOIN ROOM C
    ON B.ROOM_ID = C.ROOM_ID
    WHERE A.PARTY_ID = P_PARTY_ID;

    IF(V_COUNT >= V_MAX) THEN
        RETURN '인원 최대 파티';
    END IF;

    RETURN '신청 가능한 파티';
END;
*/


테마 이미지
테마명
날짜
시간
파티명
평균 매너온도
평균 나이
현재 인원 수




SELECT A.PARTY_ID ,D.ROOM_IMG, D.ROOM_NAME, TO_CHAR(C.OPEN_AT,'YYYY-MM-DD'), TO_CHAR(C.OPEN_AT,'HH24:MI'), A.PARTY_NAME, E.AVG, E.TEMP, E.COUNT
FROM PARTY A
JOIN PARTY_ROOM B
ON A.PARTY_ID = B.PARTY_ID
JOIN RES_OPEN C
ON B.RES_OPEN_ID = C.RES_OPEN_ID
JOIN ROOM D
ON C.ROOM_ID = D.ROOM_ID
JOIN 
(
    SELECT PARTY_ID,TRUNC(NVL(AVG(AGE),-1),1) AS AVG, TRUNC(NVL(AVG(TEMP),-1),1) AS TEMP, COUNT(*) AS COUNT
    FROM VW_PARTY_ACTIVE_MEMBER
    GROUP BY PARTY_ID
) E
ON A.PARTY_ID = E.PARTY_ID
WHERE A.PARTY_ID = 1
;


SELECT A.ROOM_ID AS themeId, A.ROOM_IMG AS imagePath, A.ROOM_NAME AS themeName
, B.GENRE_NAME AS genre, A.DURATION AS duration, A.DIFFICULTY AS difficulty
, A.HORROR_GRADE AS horror, A.MIN_PLAYERS AS minPlayers, A.MAX_PLAYERS AS maxPlayers
, A.PRICE AS price
FROM ROOM A
JOIN ROOM_GENRE B
ON A.GENRE_ID = B.GENRE_ID
JOIN CAFE C
ON A.CAFE_ID = C.CAFE_ID
WHERE INSTR(C.CAFE_NAME,4) > 0;




SELECT *
FROM CAFE;

SELECT *
FROM ROOM;

SELECT *
FROM REVIEW;

SELECT TRUNC(NVL(AVG(A.DIFFICULTY),0),0) AS DIFFICULTY
,TRUNC(NVL(AVG(A.HORROR),0),0) AS HORROR
,TRUNC(NVL(AVG(A.ACTIVITY),0),0) AS ACTIVITY
,TRUNC(NVL(AVG(A.IMMERSION),0),0) AS IMMERSION
,TRUNC(NVL(AVG(A.SATISFACTION),0),0) AS SATISFACTION
FROM REVIEW A
JOIN ATTENDANCE_DETAIL B
ON A.DETAIL_ID = B.DETAIL_ID
JOIN ATTENDANCE C
ON B.ATTENDANCE_ID = C.ATTENDANCE_ID
JOIN RESERVATION D
ON C.RESERVATION_ID = D.RESERVATION_ID
JOIN PARTY_ROOM E
ON D.PARTY_ID = E.PARTY_ID
JOIN RES_OPEN F
ON E.RES_OPEN_ID = F.RES_OPEN_ID
JOIN ROOM G
ON G.ROOM_ID = F.ROOM_ID
WHERE G.ROOM_ID = 1
;


SELECT *
FROM ATTENDANCE_DETAIL;

SELECT *
FROM ATTENDANCE;

SELECT *
FROM RESERVATION;

SELECT *
FROM PARTY_ROOM;


SELECT *
FROM ROOM;




SELECT TRUNC(NVL(AVG(A.DIFFICULTY),0),0) AS DIFFICULTY
,TRUNC(NVL(AVG(A.HORROR),0),0) AS HORROR
,TRUNC(NVL(AVG(A.ACTIVITY),0),0) AS ACTIVITY
,TRUNC(NVL(AVG(A.IMMERSION),0),0) AS IMMERSION
,TRUNC(NVL(AVG(A.SATISFACTION),0),0) AS SATISFACTION
FROM REVIEW A
JOIN ATTENDANCE_DETAIL B
ON A.DETAIL_ID = B.DETAIL_ID
JOIN ATTENDANCE C
ON B.ATTENDANCE_ID = C.ATTENDANCE_ID
JOIN RESERVATION D
ON C.RESERVATION_ID = D.RESERVATION_ID
JOIN PARTY_ROOM E
ON D.PARTY_ID = E.PARTY_ID
JOIN RES_OPEN F
ON E.RES_OPEN_ID = F.RES_OPEN_ID
JOIN ROOM G
ON G.ROOM_ID = F.ROOM_ID
WHERE G.ROOM_ID = 1



SELECT C.NICKNAME nickName, A.SATISFACTION satisfaction, A.DIFFICULTY difficulty
, A.HORROR horror, A.ACTIVITY activity, A.IMMERSION immersion, A.REVIEW_COMMENT reviewComment
FROM REVIEW A
JOIN ATTENDANCE_DETAIL B
ON A.DETAIL_ID = B.DETAIL_ID
JOIN USER_ACCOUNT C
ON B.USER_ID = C.USER_ID
JOIN ATTENDANCE D
ON B.ATTENDANCE_ID = D.ATTENDANCE_ID
JOIN RESERVATION E
ON D.RESERVATION_ID = E.RESERVATION_ID
JOIN PARTY_ROOM F
ON E.PARTY_ID = F.PARTY_ID
JOIN RES_OPEN G
ON F.RES_OPEN_ID = G.RES_OPEN_ID
WHERE G.ROOM_ID = 1
ORDER BY A.REVIEW_ID DESC


SELECT *
FROM REVIEW;


SELECT RES_OPEN_ID AS slotId,TO_CHAR(OPEN_AT,'YYYY-MM-DD') as resDate, TO_CHAR(OPEN_AT, 'HH24:MI') as resTime , FN_RESERVATION_CHECK(RES_OPEN_ID) AS status
FROM RES_OPEN
WHERE ROOM_ID = 1 AND OPEN_AT > SYSDATE + 1
ORDER BY OPEN_AT ASC


SELECT FN_RESERVATION_CHECK(RES_OPEN_ID)
FROM RES_OPEN
;
